//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgnaPanel.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AgnaPanel.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon agna_wing {
            get {
                object obj = ResourceManager.GetObject("agna_wing", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon agna_wing_flat_red {
            get {
                object obj = ResourceManager.GetObject("agna_wing_flat_red", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;agna-scene&gt;
        ///  &lt;id&gt;&lt;/id&gt;
        ///  &lt;fields&gt;
        ///    &lt;main&gt;
        ///      &lt;field name=&quot;to&quot; color=&quot;#000000&quot;&gt;&lt;/field&gt;
        ///      &lt;field name=&quot;ev&quot; color=&quot;#000000&quot;&gt;&lt;/field&gt;
        ///      &lt;field name=&quot;ma&quot; color=&quot;#000000&quot;&gt;&lt;/field&gt;
        ///      &lt;field name=&quot;an&quot; color=&quot;#000000&quot;&gt;&lt;/field&gt;
        ///      &lt;field name=&quot;mu&quot; color=&quot;#000000&quot;&gt;&lt;/field&gt;
        ///      &lt;field name=&quot;p1&quot; color=&quot;#000000&quot;&gt;&lt;/field&gt;
        ///      &lt;field name=&quot;p2&quot; color=&quot;#000000&quot;&gt;&lt;/field&gt;
        ///      &lt;field name=&quot;s1&quot; color=&quot;#000000&quot;&gt;&lt;/field&gt;
        ///      &lt;field name=&quot;s2&quot; color= [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string agnascene_clean {
            get {
                return ResourceManager.GetString("agnascene_clean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap challonge {
            get {
                object obj = ResourceManager.GetObject("challonge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap music_note {
            get {
                object obj = ResourceManager.GetObject("music_note", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap right_arrow {
            get {
                object obj = ResourceManager.GetObject("right_arrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;agna-settings&gt;
        ///	&lt;window&gt;
        ///    &lt;ontop enabled=&quot;false&quot; /&gt;
        ///		&lt;taskbar enabled=&quot;true&quot; /&gt;
        ///		&lt;tray enabled=&quot;false&quot; minimize=&quot;false&quot; close=&quot;false&quot; /&gt;
        ///	&lt;/window&gt;
        ///	&lt;chat&gt;
        ///		&lt;username /&gt;
        ///		&lt;oauth /&gt;
        ///    &lt;channel /&gt;
        ///    &lt;acceptCmds enabled=&quot;true&quot; /&gt;
        ///	&lt;/chat&gt;
        ///	&lt;recent max=&quot;10&quot; load=&quot;true&quot; /&gt;
        ///	&lt;autocomplete&gt;
        ///		&lt;rounds&gt;
        ///			&lt;round&gt;Winners Round&lt;/round&gt;
        ///			&lt;round&gt;Winners Quarters&lt;/round&gt;
        ///			&lt;round&gt;Winners Semis&lt;/round&gt;
        ///			&lt;round&gt;Winners Finals&lt;/round&gt;
        ///			&lt;round&gt;Los [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string settings_clean {
            get {
                return ResourceManager.GetString("settings_clean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap swap_camera {
            get {
                object obj = ResourceManager.GetObject("swap_camera", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap swap_characters {
            get {
                object obj = ResourceManager.GetObject("swap_characters", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap swap_players {
            get {
                object obj = ResourceManager.GetObject("swap_players", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
